In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from supervised_learning.regression import Regression

from sklearn.model_selection import train_test_split

from sklearn import metrics

In [ ]:
df = pd.read_csv('../data/real_estate.csv')

In [ ]:
X=df.drop('Y house price of unit area', axis=1)

In [ ]:
y= df['Y house price of unit area']

In [ ]:
X.shape, y.shape

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)
# 只取X2 house age这一列
X_train = X_train['X2 house age']
X_test = X_test['X2 house age']
# to numpy
X_train = X_train.to_numpy().reshape(-1,1)
X_test = X_test.to_numpy().reshape(-1,1)
y_train = y_train.to_numpy()
y_test = y_test.to_numpy()

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

In [ ]:
# print a chart of the X_train and y_train
plt.scatter(X_train, y_train)
plt.show()

In [ ]:
# 这里我们认为，房龄越大，房价越低，应该存在线性回归关系
# 所以我们选择一个线性回归模型

model = Regression(2000,0.00001)
model.initialize_weights_and_bias(1)
# X_train = X_train.reshape(-1,1)
# X_train.shape
# model.w.shape, X_train.shape, y_train.shape
model.fit(X_train, y_train)
# 看一下training_errors
plt.plot(model.training_errors)

In [1]:
# 最后在plt上，将线性回归的结果画出来, 包括model.w[0]和model.b
plt.scatter(X_train, y_train)
plt.plot(X_train, model.w[0]*X_train + model.b, 'r')
plt.show()
model.b


NameError: name 'plt' is not defined

In [ ]:
# 打印一下w和b
model.w, model.b

In [13]:
a = np.array([2,1])



array([4, 1])

In [5]:
a,b,c


(array([[1, 2, 3]]),
 array([[3],
        [4],
        [5]]),
 array([[ 3,  6,  9],
        [ 4,  8, 12],
        [ 5, 10, 15]]))

In [6]:
np.dot(a,a)

array([[26]])

In [14]:
def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    
    # (≈ 1 line of code)
    # s = 
    # YOUR CODE STARTS HERE
    s = 1/(1+np.exp(-x))
    
    # YOUR CODE ENDS HERE
    

    return s

In [15]:
v = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])



In [16]:
v.shape

(3, 3, 2)

In [17]:
v2 =  v.reshape((v.shape[0] * v.shape[1], v.shape[2]))

In [18]:
v2.shape

(9, 2)

In [26]:
v3=v2.reshape(3, 1, -1)  
np.zeros((3, 1, 2))


array([[[0., 0.]],

       [[0., 0.]],

       [[0., 0.]]])

print(1)

In [27]:
def propagate(w, b, X, Y):
    """
    Implement the cost function and its gradient for the propagation explained above

    Arguments:
    w -- weights, a numpy array of size (num_px * num_px * 3, 1)
    b -- bias, a scalar
    X -- data of size (num_px * num_px * 3, number of examples)
    Y -- true "label" vector (containing 0 if non-cat, 1 if cat) of size (1, number of examples)

    Return:
    grads -- dictionary containing the gradients of the weights and bias
            (dw -- gradient of the loss with respect to w, thus same shape as w)
            (db -- gradient of the loss with respect to b, thus same shape as b)
    cost -- negative log-likelihood cost for logistic regression
    
    Tips:
    - Write your code step by step for the propagation. np.log(), np.dot()
    """
    
    m = X.shape[1]
    
    # FORWARD PROPAGATION (FROM X TO COST)
    #(≈ 2 lines of code)
    # compute activation
    # A = ...
    # compute cost by using np.dot to perform multiplication. 
    # And don't use loops for the sum.
    # cost = ...                                
    # YOUR CODE STARTS HERE
    
    A = sigmoid(np.dot(w.T, X)+b)
    cost = -np.sum(Y * np.log(A)+(1-Y)*(np.log(1-A)))/m
    
    # YOUR CODE ENDS HERE

    # BACKWARD PROPAGATION (TO FIND GRAD)
    #(≈ 2 lines of code)
    # dw = ...
    # db = ...
    # YOUR CODE STARTS HERE

    dw = np.dot(X, (A-Y).T)/m
    print(f' {X.shape},   {A.shape},   {Y.shape},   {dw.shape}')
    db = np.sum(A-Y)/m
    
    # YOUR CODE ENDS HERE
    cost = np.squeeze(np.array(cost))

    
    grads = {"dw": dw,
             "db": db}
    
    return grads, cost

In [ ]:
def model(X_train, Y_train, X_test, Y_test, num_iterations=2000, learning_rate=0.5, print_cost=False):
    """
    Builds the logistic regression model by calling the function you've implemented previously
    
    Arguments:
    X_train -- training set represented by a numpy array of shape (num_px * num_px * 3, m_train)
    Y_train -- training labels represented by a numpy array (vector) of shape (1, m_train)
    X_test -- test set represented by a numpy array of shape (num_px * num_px * 3, m_test)
    Y_test -- test labels represented by a numpy array (vector) of shape (1, m_test)
    num_iterations -- hyperparameter representing the number of iterations to optimize the parameters
    learning_rate -- hyperparameter representing the learning rate used in the update rule of optimize()
    print_cost -- Set to True to print the cost every 100 iterations
    
    Returns:
    d -- dictionary containing information about the model.
    """
    # (≈ 1 line of code)   
    # initialize parameters with zeros
    # and use the "shape" function to get the first dimension of X_train
    # w, b = ...
    
    #(≈ 1 line of code)
    # Gradient descent 
    # params, grads, costs = ...
    
    # Retrieve parameters w and b from dictionary "params"
    # w = ...
    # b = ...
    
    # Predict test/train set examples (≈ 2 lines of code)
    # Y_prediction_test = ...
    # Y_prediction_train = ...
    
    # YOUR CODE STARTS HERE
    w, b = np.zeros((X_train.shape[0], 1)), 0
    
    params, grads, costs = optimize(w,b,X_train,Y_train,num_iterations,learning_rate,print_cost)
    w = params['w']
    b = params['b']
    Y_prediction_test = predict(w,b,X_test)
    Y_prediction_train = predict(w,b,X_train)
    
    
    # YOUR CODE ENDS HERE

    # Print train/test Errors
    if print_cost:
        print("train accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_train - Y_train)) * 100))
        print("test accuracy: {} %".format(100 - np.mean(np.abs(Y_prediction_test - Y_test)) * 100))

    
    d = {"costs": costs,
         "Y_prediction_test": Y_prediction_test, 
         "Y_prediction_train" : Y_prediction_train, 
         "w" : w, 
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}
    
    return d